#!/bin/bash

# Detect Docker Compose version
if docker compose version > /dev/null 2>&1; then
    DOCKER_COMPOSE="docker compose"
else
    DOCKER_COMPOSE="docker-compose"
fi

echo "=========================================================="
echo "          MarkFlow: Global Setup & Installation           "
echo "=========================================================="
echo ""

# 1. Ask for Ports
read -p "Enter HTTP port to use on host (default: 80): " HTTP_PORT
HTTP_PORT=${HTTP_PORT:-80}

read -p "Enter HTTPS port to use on host (default: 443): " HTTPS_PORT
HTTPS_PORT=${HTTPS_PORT:-443}

# 2. Ask for Domain
read -p "Enter your domain name (e.g., docs.example.com): " DOMAIN_NAME
if [ -z "$DOMAIN_NAME" ]; then
    echo "Error: Domain name is required."
    exit 1
fi

# 3. Ask for Email
read -p "Enter your email for SSL alerts (optional, press Enter to skip): " CERTBOT_EMAIL

# 4. Create/Overwrite .env at root
echo "### MarkFlow Configuration (Generated by setup.sh)" > ../.env
echo "HTTP_PORT=$HTTP_PORT" >> ../.env
echo "HTTPS_PORT=$HTTPS_PORT" >> ../.env
echo "DOMAIN_NAME=$DOMAIN_NAME" >> ../.env
echo "CERTBOT_EMAIL=$CERTBOT_EMAIL" >> ../.env

echo ""
echo "----------------------------------------------------------"
echo " Configuration saved to .env:"
echo " - HTTP Port:  $HTTP_PORT"
echo " - HTTPS Port: $HTTPS_PORT"
echo " - Domain:     $DOMAIN_NAME"
echo " - Email:      ${CERTBOT_EMAIL:-None}"
echo "----------------------------------------------------------"
echo ""

# 5. Build Containers
echo "### Building and starting containers..."
$DOCKER_COMPOSE build
$DOCKER_COMPOSE up -d

# 6. Ask about SSL
echo ""
read -p "Do you want to initialize SSL certificates (Certbot) right now? (y/N): " init_ssl
if [[ "$init_ssl" =~ ^[Yy]$ ]]; then
    if [ -f "./init-letsencrypt.sh" ]; then
        chmod +x init-letsencrypt.sh
        # Run SSL script. It will read the values we just saved to .env
        ./init-letsencrypt.sh
    else
        echo "Error: init-letsencrypt.sh not found."
    fi
else
    echo "Skipping SSL initialization. You can run ./init-letsencrypt.sh later."
fi

echo ""
echo "=========================================================="
echo "          Setup Complete! MarkFlow is starting.           "
echo "=========================================================="
echo " Visit: http://$DOMAIN_NAME (or https if SSL was enabled)"
